SuperheroesCreator/Models/ErrorViewModel.cs
using System;

namespace SuperheroesCreator.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SuperheroesCreator/Models/Superhero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SuperheroesCreator.Models
{
    public class Superhero
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Superhero Name")]
        public string SuperheroName { get; set; }
        [Display(Name = "Alter Ego")]
        public string AlterEgo { get; set; }
        [Display(Name = "Primary Ability")]
        public string PrimaryAbility { get; set; }
        [Display(Name = "Secondary Ability")]
        public string SecondaryAbility { get; set; }
        [Display(Name = "Catch phrase")]
        public string Catchphrase { get; set; }
    }
}

SuperheroesCreator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SuperheroesCreator.Models;

namespace SuperheroesCreator.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SuperheroesCreator/Controllers/SuperheroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SuperheroesCreator.Data;
using SuperheroesCreator.Models;

namespace SuperheroesCreator.Controllers
{
    public class SuperheroController : Controller
    {   //in order to add to data table, create private member variable and constructor
        private ApplicationDbContext _context;
        //constructor is using built-in dependency injection to inject applicationDBcontext
        //into this constroller to be used
        public SuperheroController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: SuperheroController
        public ActionResult Index()
        {
            //List<Superhero> heroList = new List<Superhero>();
            var superheroes = _context.Superheroes.ToList();
            return View(superheroes);
        }

        // GET: SuperheroController/Details/5
        public ActionResult Details(int id)
        {
            Superhero heroDetails = _context.Superheroes.Find(id);
            return View(heroDetails);
        }

        // GET: SuperheroController/Create
        public ActionResult Create()
        {
       
            return View();
        }

        // POST: SuperheroController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Superhero superhero)
        {
            try
            {
                //todo: add insert logic here
                _context.Superheroes.Add(superhero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SuperheroController/Edit/5
        public ActionResult Edit(int id)
        {
            Superhero superhero = _context.Superheroes.Find(id);
            if (superhero == null)
            {
                return HttpNotFound();
            }
            return View(superhero);
        }

        private ActionResult HttpNotFound()
        {
            throw new NotImplementedException();
        }

        // POST: SuperheroController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Superhero superhero)
        {
            try
            {
                //linq alternative:
                //var hero = _context.Superheroes.Where(s => s.Id == superhero.Id).FirstOrDefault();
                //_context.Superheroes.Remove(hero);
                //_context.Superheroes.Add(superhero);

                _context.Superheroes.Update(superhero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SuperheroController/Delete/5
        public ActionResult Delete(int id)
        {
            Superhero superhero = _context.Superheroes.Find(id);

            if (superhero == null)
            {
                return HttpNotFound();
            }
            return View(superhero);
        }

        // POST: SuperheroController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Superhero superhero)
        {
            try
            {
                //linq alternative:
                //var heroToDelete = _context.Superheroes.Where(s => s.Id == id).ToList();
                //foreach (var hero in heroToDelete)
                //{
                //    _context.Superheroes.Remove(hero);
                //}
                   
                var heroToDelete = _context.Superheroes.Find(id);
                _context.Superheroes.Remove(heroToDelete);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SuperheroesCreator/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <img style="width: 50%; margin-top: 10%" src="~/images/deadpool2.jpg" alt="Deadpool" />
    <h1>"I may be super, but I'm no hero."</h1>
   
</div>

SuperheroesCreator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperheroesCreator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Superheroes Creator</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Superhero" asp-action="Index">Index</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    @*<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                    </li>*@
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>

        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SuperheroesCreator</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SuperheroesCreator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SuperheroesCreator/Views/Superhero/Create.cshtml
@model SuperheroesCreator.Models.Superhero

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Superhero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SuperheroName" class="control-label"></label>
                <input asp-for="SuperheroName" class="form-control" />
                <span asp-validation-for="SuperheroName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgo" class="control-label"></label>
                <input asp-for="AlterEgo" class="form-control" />
                <span asp-validation-for="AlterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimaryAbility" class="control-label"></label>
                <input asp-for="PrimaryAbility" class="form-control" />
                <span asp-validation-for="PrimaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryAbility" class="control-label"></label>
                <input asp-for="SecondaryAbility" class="form-control" />
                <span asp-validation-for="SecondaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Catchphrase" class="control-label"></label>
                <input asp-for="Catchphrase" class="form-control" />
                <span asp-validation-for="Catchphrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperheroesCreator/Views/Superhero/Delete.cshtml
@model SuperheroesCreator.Models.Superhero

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Superhero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SuperheroName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SuperheroName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlterEgo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlterEgo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrimaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrimaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Catchphrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Catchphrase)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SuperheroesCreator/Views/Superhero/Details.cshtml
@model SuperheroesCreator.Models.Superhero

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Superhero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SuperheroName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SuperheroName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlterEgo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlterEgo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrimaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrimaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Catchphrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Catchphrase)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SuperheroesCreator/Views/Superhero/Edit.cshtml
@model SuperheroesCreator.Models.Superhero

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Superhero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SuperheroName" class="control-label"></label>
                <input asp-for="SuperheroName" class="form-control" />
                <span asp-validation-for="SuperheroName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgo" class="control-label"></label>
                <input asp-for="AlterEgo" class="form-control" />
                <span asp-validation-for="AlterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimaryAbility" class="control-label"></label>
                <input asp-for="PrimaryAbility" class="form-control" />
                <span asp-validation-for="PrimaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryAbility" class="control-label"></label>
                <input asp-for="SecondaryAbility" class="form-control" />
                <span asp-validation-for="SecondaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Catchphrase" class="control-label"></label>
                <input asp-for="Catchphrase" class="form-control" />
                <span asp-validation-for="Catchphrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperheroesCreator/Views/Superhero/Index.cshtml
@model IEnumerable<SuperheroesCreator.Models.Superhero>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SuperheroName)
            </th>
           
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SuperheroName)
            </td>
         
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>